# Building the artifacts

name: "build-artifacts"

on:
  push:
    branches: [ main ]

jobs:
  publish-tauri:
    strategy:
        fail-fast: true
        matrix:
          platform: [macos-latest, ubuntu-18.04, windows-latest]
    runs-on:  ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v2
    - uses: Swatinem/rust-cache@v1
      with:
        working-directory: src-tauri
    - name: setup node
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: get version
      run: echo "PACKAGE_VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV
    - name: get release message
      run: echo "RELEASE_MESSAGE=$(node -p "require('./package.json').release_message")" >> $GITHUB_ENV
    - name: install Rust stable
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: install webkit2gtk (ubuntu only)
      if: matrix.platform == 'ubuntu-18.04'
      run: |
        sudo apt-get update
        sudo apt-get install -y webkit2gtk-4.0
    - name: install app dependencies and build it
      run: yarn && yarn tauri build
    - uses: tauri-apps/tauri-action@v0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        distPath: 'dist'
        tagName: app-v${{ env.PACKAGE_VERSION }}
        releaseName: "Desktop app v${{ env.PACKAGE_VERSION }}"
        releaseBody: ${{ env.RELEASE_MESSAGE }}
        releaseDraft: false
        prerelease: false